# file: iptables/tasks/main.yml

---
  - name: Flush existing firewall rules
    iptables:
      flush: true

  - name: Allow related and established connections
    iptables:
      chain: INPUT
      ctstate: ESTABLISHED,RELATED
      jump: ACCEPT

  - name: Allow port ping traffic
    iptables:
      chain: INPUT
      protocol: icmp
      jump: ACCEPT

  - name: Allow port 22 / SSH traffic
    iptables:
      chain: INPUT
      destination_port: 22
      protocol: tcp
      jump: ACCEPT

  - name: Allow port 80 / HTTP traffic
    iptables:
      chain: INPUT
      destination_port: 80
      jump: ACCEPT
      protocol: tcp

  - name: Allow port 8000 / HTTP traffic
    iptables:
      chain: INPUT
      destination_port: 8000
      jump: ACCEPT
      protocol: tcp

  - name: Allow port 8002 / HTTP traffic
    iptables:
      chain: INPUT
      destination_port: 8002
      jump: ACCEPT
      protocol: tcp

  - name: Allow port 5432 / PostgreSQL
    iptables:
      chain: INPUT
      destination_port: 5432
      jump: ACCEPT
      protocol: tcp

  - name: Allow port 2049 (tcp) / NFS
    iptables:
      chain: INPUT
      destination_port: 2049
      jump: ACCEPT
      protocol: tcp

  - name: Allow port 2049 (udp) / NFS
    iptables:
      chain: INPUT
      destination_port: 2049
      jump: ACCEPT
      protocol: udp

  - name: Allow port 111 (tcp) / Portmapper
    iptables:
      chain: INPUT
      destination_port: 111
      jump: ACCEPT
      protocol: tcp

  - name: Allow port 111 (udp) / Portmapper
    iptables:
      chain: INPUT
      destination_port: 111
      jump: ACCEPT
      protocol: udp

  - name: Allow port 11211 (tcp) / Memcache
    iptables:
      chain: INPUT
      destination_port: 11211
      jump: ACCEPT
      protocol: tcp

  - name: Drop any traffic without rule
    iptables:
      chain: INPUT
      jump: DROP
